Extra exercise done
paskag/basic_exercises pull request #1
Opened 2021-11-30 15:31 UTC by paskag

2021-11-30 22:48 UTC, TovarischSukhov requested changes

2021-11-30 22:48 UTC, TovarischSukhov commented on for_challenges.py
> +    if is_male[name] == True:
кое что лишнее =)

2021-11-30 22:48 UTC, TovarischSukhov commented on for_challenges.py
> +        if name == group[-1]:
а если 2 одинаковых имени в одной группе?

2021-11-30 22:48 UTC, TovarischSukhov commented on for_dict_challenges.py
> +    if value["man"] > max_man:
max_man не обновляешь

2021-12-01 04:19 UTC, paskag commented on for_challenges.py
> +    if is_male[name] == True:
Можно просто написать
`if is_male[name]:`

Ты это имеешь в виду?

2021-12-01 04:26 UTC, paskag commented on for_challenges.py
> +        if name == group[-1]:
исправил

2021-12-01 04:27 UTC, paskag commented on for_dict_challenges.py
> +    if value["man"] > max_man:
да, забыл
исправил

2021-12-03 16:46 UTC, merged